### PR TITLE
Patch sets to test Linux Packages. Patch sets predominantly contains …

### PR DESCRIPTION
**Pull request by PoornimaNayak**
…wrappers to trigger tests in Linux source packages.

### CODE REVIEW

**Comment by PoornimaNayak** [comment]
Fixed all failures observed during CI check

**Comment by lmr** [comment]
OK, let me take a look

**Comment by lmr** [comment]
Hi Poornima, some comments:

1) There's a lot of shell script in there, that seems to be easily translatable to python
2) Non py files have a lot of whitespace
3) The scope of the PR is really large, so what I can do is to do a poor diagonal reading of the files, nothing that will be close to a thorough review.

**Comment by lmr** [comment]
Also, this PR could've been easily merged into a single commit, to avoid showing up the intermediate fixup steps. I took the liberty and generated #75 with all this PR's content, all merged up, with a slightly better commit message. I'm closing this one and will merge #75.

**Pull request closed without merging**
