### PR TITLE
.travis.yml: Update origin of autotest package

### PR DESCRIPTION
**Pull request by lmr**
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>

### CODE REVIEW

**Comment by ldoktor** [comment]
Hey, Lucas, thanks for the changes. I'm only wondering about the 2.4 compatibility, did you try it? Were there extensive problems or why did you chose 2.6 instead?

**Comment by lmr** [comment]
@ldoktor, good point, but there's no way to reliably test 2.4 in Travis CI. I guess at this point we have no way of doing that other than a highly customized internal CI system, which I think we are short handed to deliver.

**Comment by lmr** [comment]
@ldoktor we're probably better off dropping 2.4 compatibility entirely

**Comment by ldoktor** [comment]
oh, true. 2.6 is the oldest supported version. Thanks.

**Pull request merged**
